[build]
  publish = "."
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirect admin to admin/index.html
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

# Enable Netlify Identity
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
